### ISSUE TITLE
Still depending on ex-navigation?

### ISSUE THREAD

**Issue by arnthorsnaer** [spencercarli/ex-navigation-to-react-navigation#2]
I might have missed something but it looks like in your project that your still depending on and importing @expo/ex-navigation - why is this?

**Comment by spencercarli** [comment]
It's just left there because of the incremental nature of this repo. It could be removed once the Drawer migration is complete.

**Comment by spencercarli** [comment]
Actually, I should link to the blog post that walks through the migration process in the repo. That could be the missing link :) https://hackernoon.com/migrate-from-exnavigation-to-react-navigation-1af661ec5082

**Comment by darrenfurr** [comment]
I think you want to link to the Diff...
https://github.com/spencercarli/ex-navigation-to-react-navigation/compare/TabNavigation-to-TabNavigator...DrawerNavigation-to-DrawerNavigator#diff-2018087f584c4398b5c3a23fc0e5f9db
